### ISSUE TITLE
Add support for different directory

### ISSUE THREAD

**Issue by CaptainCrasi** [joydip007x/prisma-unify007x#3]
Right now I am sadly unable to use this extension as my Prisma file is nested from the root folder.

I suggest you add a config file to specify where we would like to read from and where to output the Prisma file. Maybe temporarily you could release a `--read` and `--ouput` flag on `npx prisma-multischema`.

I recommend you keep this as high priority because it seems quite easy to add and makes the extension unusable for someone like me without it.

**Comment by joydip007x** [comment]
I understood. @CaptainCrasi .
I will try to fix that issue as soon as i can.

**Comment by brandanking-decently** [comment]
Hi, I can see this has been marked as complete, but I see any documentation stating how to do this. Has this actually been fixed in the current release version?

**Comment by joydip007x** [comment]
@brandanking-decently 

I am working on this.
This is not fixed yet,  
This feature will be added on next release of this package. 
Thanks  🙂

**Comment by omrqs** [comment]
This improvement already fixed?

**Comment by omrqs** [comment]
Now Prisma has native support for multiple schema files.
https://www.prisma.io/blog/organize-your-prisma-schema-with-multi-file-support
